### ISSUE TITLE
make3rd.x64.bat libjpeg perl script enhancment

### ISSUE THREAD

**Issue by jasin** [geoffmcl/test-sg#8]
@geoffmcl 
Libjpeg is a PITA using versions GT MSVC10

I'd like to discuss the thought of using the perl script to not only change what it does now, but also add another line, specifically if MSVC EQ 12 <PlatformToolset>v120</PlatformToolset> to jpeg.vcxproj file. 

Then instead of calling msbuild jpeg.sln call msbuild jpeg.vcxproj  instead. This would ease the need for a special source zip to compile libjpeg. Thoughts and ideas on how this can be done??

**Comment by geoffmcl** [comment]
@jasin agree 100%. If it is a PITA in MSVC10 plus, then this **MUST** be fixed... for sure...

You are suggesting more perl script change... that is fine... to do what, exactly?

The problem I see is that after vc10, the zip provides no more solutions... 

I remember seeing one of your changes, like `nmake -f makefile.vc setup-vc12`, ie some other vc target number, but looking at the source, from the 'a' zip, and a 'b' zip, there is no such target!

And somehow, I do not think changing the `msbuild` target from the .sln to the .vxproj would achieve anything... but maybe...

Ideally, I would like to download a libjpeg source that used cmake, ie had a CMakeLists.txt, as part of the source, then all would be too **easy** ;=))

What suggestions do you have?

**Comment by geoffmcl** [comment]
As suggested, one idea is to have a convenient **new** source...

So I zipped up a 27/08/2013  14:11 1,098,356 jpegsrc9c.zip, which has a CMakeLists.txt ...

So the URL is http://geoffair.org/tmp/jpegsrc9c.zip

It unzips to `jpeg-9`, so this must be renamed to `jpeg-source`...

Then create a `jpeg-build` and build it, like a dozen others components... installing directly into 3rd... first just in Releasse...

Later, when make3rd.x84 is called from within `d-and-c.x64.bat`, then if the /D on, then in Debug and RelWithDebInfo configs...

Maybe try it out, in a branch, if you get a chance...

Edit: fix http addr

**Comment by jasin** [comment]
Oh I see it edited my first post and removed the elements.

The reason I want to change to calling jpeg.vcxproj is because with the addition of one line to this file (vcxproj) we can build on MSVC 12 without needing to provide another third party source. If we call msbuild with an appropriate jpeg.sln for MSVC 12 things get dramatically harder to get it to compile. 

the difference between MSVC 10 and 12 concerning the project SLN files is a completely different style and lots of new tag elements.
the difference between MSVC 10 and 12 concerning the vcxproj files is **one line**. 

Add this line to jpeg.vcxproj
`<PlatformToolset>v120</PlatfomToolset>`

and you can now use the original source, call nmake -f makefile.vc setup-v10 and msbuild jpeg.vcxproj will compile. As long as you add that **one** line. I wish there was any easier way to convert this jpeg.sln jpeg.vcxproj but it does not work until I load it specifically into MSVC. This is why i want to use the perl script to add the one element to the project file before running msbuild and avoid all the mess of providing a modified MSVC 12 *sln file. 

I don't know anything about perl, but seeing as how you are using it to substitute text I figured we could use it to find a line and then insert a new line right after?

**Comment by geoffmcl** [comment]
@jasin makes sense, use compatible .vcxproj file... but where to add that line?

It is one easy thing to make a substitution in an existing line...

It is a bigger ball game to insert a new line... that gets into parsing a lot more that that script does...

But not impossible, but where does your MSVC12 save it to after conversion?

Making the existing stuff work also works for me...

**Comment by jasin** [comment]
The only difference I could find between MSVC 10 and MSVC 12 was the PlatformToolset line that specified to MSVC to use v120, otherwise it will try to locate a *dll that is part of MSVC 10 and fail.
The line follows the CharacterSet tag and must be contained inside the parent PropertyGroup element. 
`<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'" Label="Configuration">`
    `...`
    `<CharacterSet>Unicode</CharacterSet>`
    `<PlatformToolset>v120</PlatformToolset>`
`</PropertyGroup>`

Edit: It is equivalent to opening up the projects properties window in MSVC and then under **Configuration Properties > General > Platform Toolset** adjust it to use v90 v100 v120 etc. Maybe you have these options in MSVC10 for other previous versions as well?

**Comment by geoffmcl** [comment]
Hmmm, well what we could try is ...

```
s/<CharacterSet>Unicode</CharacterSet>/ with   <CharacterSet>Unicode</CharacterSet>\n<PlatformToolset>v120</PlatformToolset>/
```

That is provided there is only one such `<CharacterSet>Unicode</CharacterSet>` line in the file... else need a unique trigger...

Now in perl code terms that is - 

```
@echo         $line =~ s/\<CharacterSet\>Unicode\<\/CharacterSet\>/\<CharacterSet\>Unicode\<\/CharacterSet\>\n\<PlatformToolset\>v120\<\/PlatformToolset\>/g; >>%PERL_FIL%
```

but need to test the code... can you cut it in and try?

This is where I often set a jump, to go straight to the test build...

**Comment by jasin** [comment]
Yeah, it worked. But I had to edit rep32w64.pl by hand. Not sure why the echo command fails. 

I am not seeing the issue, but for sure if you can get the batch cmd to write the perl script correctly, it will work here. Then we can broaden the scope by setting PlatformToolset to **v%_MSVC%0**

**Comment by geoffmcl** [comment]
So if you can hand paste it, and it works, then it should not be a problem to fix the echo to do the same thing...

And yes, maybe expand it by using %_MSVC%, but also limiting its inclusion with -

```
@if %MSVC% GTR 10 (
  @REM add platform toolset to ..vcxproj file
)
```

I do not need this addition to the script, and prefer running the solution, .sln, using a similar switch...

**Comment by jasin** [comment]
I'm still on the fence about this. Maybe with all this fuss we should just go ahead and provide a source using cmake and provide a decent start with all MSVC versions???

**Comment by geoffmcl** [comment]
@jasin I too sometimes have fences that I sit on ;=)) so long as that does not mean leaving a known problem... aka, doing nothing...

So think I have provided a test, in the `test-jpeg` branch... I forgot that the echo escape character is a `^`...

That does not stop us pursuing another solutions... I have posted a URL to an example... should be easy to add an alternative build of jpeg, but that needs to be written and tested...

Anyway to try this, in your fork -

```
$ cd test-sg-fork
$ git fetch upstream
$ # rebase or not
$ # but somehow merge, and
$ git checkout test-jpeg
$ cd scripts\d-and-c
$ md temp2
$ cd temp2
$ copy ..\*.bat
$ build3rd.x64
```

Or pull test-sg direct, and do the same test... hope it works...

**Comment by geoffmcl** [comment]
@jasin so this seems **fixed** ...  and moved into the `next` branch... will get around to deleting the `test-jpeg` branch shortly...

But can we close this issue? ... Or do you still want to explore other solutions? 

They say the grass is always greener on the other side of the fence... ;=))

But meantime thanks for this addition to build3rd.x64...

**Comment by geoffmcl** [comment]
@jasin just to mention this has **all** now been merged to the `master` branch, where work can continue... 

The `next` will remain frozen, until we need it again... 

```
$ git checkout master
$ git fetch upstream
$ git rebase upstream/master
$ git push
```

Just for test-sg added a version.txt file, for versioning the repo... but no big shakes... and nothing to do with scripts...

So, again, maybe we can close this? thanks...

**Comment by jasin** [comment]
Sounds good and done. I should be caught up. Thanks

BTW, it depends on which side of the fence you start on.
